[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool]

[tool.setuptools_scm]

[tool.isort]
line_length = 110
default_section = "THIRDPARTY"
known_first_party = "bagit"

[tool.coverage.run]
branch = true
include = "bagit.py"

