[tox]
requires =
    tox>=4.26
    tox-uv>=1
env_list =
    py39
    py310
    py311
    py312
    py313
    py314
    py315
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    dev
commands =
    pytest {posargs}
