name: tox
on: [push, pull_request]
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11
      - run: sudo apt-get install -qy gettext
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox
